// @flow
import {StatusBar, StyleSheet} from 'react-native';
import {Colors, Metrics} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.5)',
    paddingHorizontal: 20,
    paddingBottom: 30,
  },

  CarouseView: {
    backgroundColor: Colors.white,
    height: 59,
    width: '100%',
    borderRadius: 12,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 0.5,
    elevation: 2,
  },
  nutritionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 0.5,
    elevation: 2,
    height: 47,
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 15,
    paddingBottom: 0,
  },

  btnStyle: {
    flex: 0.5,
    height: 45,
    padding: 0,
    marginTop: 5,
    borderRadius: 6,
  },
  btnNutritionItem: {
    borderBottomWidth: 2,
    borderBottomColor: Colors.background.primary,
  },
  GraphView: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 0.5,
    elevation: 2,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
    borderRadius: 12,
    padding: 15,
  },
  circleView: {
    width: 18,
    height: 18,
    borderRadius: 9,
    marginRight: 7.5,
  },
  separator: {
    backgroundColor: '#F4F3F7',
    height: 2,
    marginTop: 15,
  },
  CaloriesTable: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 0.5,
    elevation: 2,
    backgroundColor: 'white',
    justifyContent: 'center',
    marginTop: 15,
    borderRadius: 12,
    padding: 15,
  },
  NutritentsTable: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 0.5,
    elevation: 2,
    backgroundColor: 'white',
    justifyContent: 'center',
    marginTop: 15,
    borderRadius: 12,
    padding: 13,
  },
  MacrosView: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 0.5,
    elevation: 2,
    backgroundColor: 'white',
    justifyContent: 'center',
    marginTop: 15,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
  },
});
